#----------------------------------------------------------
# common
#----------------------------------------------------------

local: &local
  adapter:  sqlite3
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000


#----------------------------------------------------------
# local
#----------------------------------------------------------

development:
  <<: *local
  database: db/development.sqlite3

test:
  <<: *local
  database: db/test.sqlite3
